### PR TITLE
Resolve #10: socket.io integration

### LINKED ISSUE #10: chore: socketio integration

### PR DESCRIPTION
**Pull request by achen930**
Socket.io implementation with chat that auto takes logged in user's name or sets user to unknown - will implement proper rendering once auth is setup

### CODE REVIEW

**Comment by achen930** [comment]
#10

**Review by angus-ng — COMMENTED** [review]
please remove dependency: ts-node. 
and files: package-lock.json, local.db

**Comment by achen930** [comment]
Resolve: removed package-lock.json, local.db, ts-node

**Review by angus-ng — APPROVED** [review]
looks good👍

**Pull request merged**
